'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Badge } from '../../components/badge';
import { Button } from '../../components/button';
import { Card } from '../../components/card';
import { Topbar } from '../../components/layout/topbar';
import { FilterChips } from '../../components/ui/filter-chips';

type AuditEvent = {
  id: string;
  proofId: string;
  action: string;
  actor: string;
  actorRole: 'User' | 'Verifier' | 'System';
  timestamp: string;
  txHash?: string;
  status: 'info' | 'success' | 'error';
  detail: string;
};

const events: AuditEvent[] = [
  {
    id: 'E-1001',
    proofId: 'VRF-2048',
    action: 'Verification Approved',
    actor: 'Verifier Demo',
    actorRole: 'Verifier',
    timestamp: '2 minutes ago',
    txHash: '0x943a12fb...8c21d4',
    status: 'success',
    detail: 'Compliance officer approved income threshold proof.',
  },
  {
    id: 'E-1000',
    proofId: 'VRF-2048',
    action: 'AI Explanation Generated',
    actor: 'System',
    actorRole: 'System',
    timestamp: '3 minutes ago',
    status: 'info',
    detail: 'LLM recommendation: Approve (confidence 94%).',
  },
  {
    id: 'E-0999',
    proofId: 'VRF-2048',
    action: 'Technical Verification Passed',
    actor: 'Verifier Demo',
    actorRole: 'Verifier',
    timestamp: '5 minutes ago',
    status: 'success',
    detail: 'All 5 verification checks passed successfully.',
  },
  {
    id: 'E-0998',
    proofId: 'VRF-2048',
    action: 'QR Scanned by Verifier',
    actor: 'Verifier Demo',
    actorRole: 'Verifier',
    timestamp: '6 minutes ago',
    status: 'info',
    detail: 'Verifier initiated verification via QR scan.',
  },
  {
    id: 'E-0997',
    proofId: 'VRF-2048',
    action: 'QR Generated by User',
    actor: 'Anonymous #a3b4c5d6',
    actorRole: 'User',
    timestamp: '7 minutes ago',
    status: 'info',
    detail: 'User generated shareable QR code (expires in 10 min).',
  },
  {
    id: 'E-0996',
    proofId: 'VRF-2048',
    action: 'Proof Stored on Ethereum',
    actor: 'System',
    actorRole: 'System',
    timestamp: '10 minutes ago',
    txHash: '0x5fbdb231...180aa3',
    status: 'success',
    detail: 'Proof hash anchored to Ethereum Sepolia testnet.',
  },
  {
    id: 'E-0995',
    proofId: 'VRF-2048',
    action: 'Zero-Knowledge Proof Generated',
    actor: 'Anonymous #a3b4c5d6',
    actorRole: 'User',
    timestamp: '12 minutes ago',
    status: 'success',
    detail: 'Groth16 proof generated for income threshold claim.',
  },
  {
    id: 'E-0994',
    proofId: 'VRF-2048',
    action: 'Document Uploaded',
    actor: 'Anonymous #a3b4c5d6',
    actorRole: 'User',
    timestamp: '15 minutes ago',
    status: 'info',
    detail: 'Salary slip (salary_slip_july.pdf, 842 KB) uploaded.',
  },
  {
    id: 'E-0993',
    proofId: 'VRF-2048',
    action: 'Claim Created',
    actor: 'Anonymous #a3b4c5d6',
    actorRole: 'User',
    timestamp: '20 minutes ago',
    status: 'info',
    detail: 'Income Threshold claim submitted.',
  },
];

function actorBadge(role: AuditEvent['actorRole']) {
  if (role === 'Verifier') return 'info' as const;
  if (role === 'System') return 'neutral' as const;
  return 'success' as const;
}

export default function AuditTrailPage() {
  const [filter, setFilter] = useState('all');

  const chips = [
    { id: 'all', label: 'All Events', count: events.length },
    { id: 'user', label: 'User', count: events.filter((e) => e.actorRole === 'User').length },
    { id: 'verifier', label: 'Verifier', count: events.filter((e) => e.actorRole === 'Verifier').length },
    { id: 'system', label: 'System', count: events.filter((e) => e.actorRole === 'System').length },
  ];

  const filtered = filter === 'all' ? events : events.filter((e) => e.actorRole.toLowerCase() === filter);

  return (
    <>
      <Topbar
        title="Audit Trail"
        subtitle="Complete, immutable log of every verification action."
        actions={
          <Button variant="outline">Export Audit Log</Button>
        }
      />

      <Card>
        <div style={{ marginBottom: 16 }}>
          <FilterChips chips={chips} activeId={filter} onSelect={setFilter} />
        </div>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {filtered.map((event, idx) => {
            const isLast = idx === filtered.length - 1;
            return (
              <div key={event.id} style={{ display: 'flex', gap: 16 }}>
                <div style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  width: 32,
                  flexShrink: 0,
                }}>
                  <div style={{
                    width: 12,
                    height: 12,
                    borderRadius: '50%',
                    backgroundColor: event.status === 'success' ? 'var(--color-success)' :
                      event.status === 'error' ? 'var(--color-error)' : 'var(--color-info)',
                    border: '3px solid var(--color-surface)',
                    boxShadow: '0 0 0 1px var(--color-border)',
                    marginTop: 6,
                  }} />
                  {!isLast && (
                    <div style={{
                      width: 1,
                      flex: 1,
                      backgroundColor: 'var(--color-border)',
                    }} />
                  )}
                </div>

                <div style={{ flex: 1, paddingBottom: isLast ? 0 : 20 }}>
                  <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'flex-start',
                    gap: 12,
                    marginBottom: 6,
                  }}>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: 14 }}>
                        {event.action}
                      </div>
                      <div style={{
                        fontSize: 12,
                        color: 'var(--color-text-secondary)',
                        marginTop: 2,
                      }}>
                        {event.detail}
                      </div>
                    </div>
                    <span style={{
                      fontSize: 11,
                      color: 'var(--color-text-muted)',
                      fontFamily: 'var(--font-mono)',
                      whiteSpace: 'nowrap',
                    }}>
                      {event.timestamp}
                    </span>
                  </div>

                  <div style={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: 6,
                    alignItems: 'center',
                    marginTop: 8,
                  }}>
                    <Badge label={event.actorRole} kind={actorBadge(event.actorRole)} />
                    <span style={{
                      fontSize: 12,
                      color: 'var(--color-text-secondary)',
                    }}>
                      {event.actor}
                    </span>
                    <span style={{
                      fontSize: 11,
                      color: 'var(--color-text-muted)',
                      fontFamily: 'var(--font-mono)',
                    }}>
                      · {event.proofId}
                    </span>
                  </div>

                  {event.txHash && (
                    <div style={{
                      marginTop: 10,
                      padding: '8px 12px',
                      backgroundColor: 'var(--color-surface-muted)',
                      borderRadius: 'var(--radius-md)',
                      border: '1px solid var(--color-border)',
                      display: 'flex',
                      alignItems: 'center',
                      gap: 8,
                    }}>
                      <span style={{
                        fontSize: 11,
                        fontWeight: 600,
                        color: 'var(--color-text-secondary)',
                        textTransform: 'uppercase',
                        letterSpacing: 0.5,
                      }}>
                        TX
                      </span>
                      <Link
                        href={`/dashboard/blockchain/${event.txHash.replace('...', '')}`}
                        className="mono"
                        style={{ flex: 1, color: 'var(--color-primary-dark)' }}
                      >
                        {event.txHash}
                      </Link>
                      <Badge label="On-chain" kind="success" />
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </Card>
    </>
  );
}
